### ISSUE TITLE
error on certain configuration with final layers less than previous one

### ISSUE THREAD

**Issue by elbraulio** [elbraulio/neuralnet#47]
this network configuration 
```java
final NeuralNetwork network = new DefaultNetwork(0, 16, 3, 16, 32, 3);
```
is not working and throws
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at com.elbraulio.neuralnet.utils.DotProduct.doubleValue(DotProduct.java:46)
	at com.elbraulio.neuralnet.utils.SigmoidDecision.doubleValue(SigmoidDecision.java:39)
	at com.elbraulio.neuralnet.epoch.DefaultEpoch.saveOutput(DefaultEpoch.java:31)
	at com.elbraulio.neuralnet.timeline.DefaultTimeLine.saveOutput(DefaultTimeLine.java:33)
	at com.elbraulio.neuralnet.unit.SaveToTimeline.feed(SaveToTimeline.java:28)
	at com.elbraulio.neuralnet.network.DefaultNetwork.feed(DefaultNetwork.java:86)
```

**Comment by elbraulio** [comment]
the following test passed with no errors.

```java
    @Test
    public void lowerLastLayer() {
        final NeuralNetwork network = new DefaultNetwork(
                0, 16, 3, 16, 32, 3
        );
        final Number[] input = new Number[]{
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
        };
        final Number[] output1 = network.feed(input);
        assertThat(
                output1[0].doubleValue(),
                is(network.feed(input)[0].doubleValue())
        );
    }
```
